language: python
python:
  - 2.7
services:
  - mongodb
install:
  - pip install -r travis.pip --allow-external webassets --allow-unverified webassets
  - pip install -e .
script:
  - nosetests --with-coverage -v
after_success:
  - coveralls --rcfile=coverage.rc
